#!/sbin/sh
# MM GUI by fordownloads for OrangeFox Recovery Project
# Based on MM by VR25

# Args: mnt, list, unmnt

# Default permissions
umask 022

mountPath=/magisk
tmp=/tmp/mmgui

is_mounted() { mountpoint -q "$1"; }

ls_mount_path() { ls -1 $mountPath | grep -v 'lost+found'; }

mount_image() {
  e2fsck -fy $IMG &>/dev/null
  if [ ! -d "$2" ]; then
    mount -o remount,rw /
    mkdir -p "$2"
  fi
  if (! is_mounted $2); then
    loopDevice=
    for LOOP in 0 1 2 3 4 5 6 7; do
      if (! is_mounted $2); then
        loopDevice=/dev/block/loop$LOOP
        [ -f "$loopDevice" ] || mknod $loopDevice b 7 $LOOP 2>/dev/null
        losetup $loopDevice $1
        if [ "$?" -eq "0" ]; then
          mount -t ext4 -o loop $loopDevice $2
          is_mounted $2 || /system/bin/toolbox mount -t ext4 -o loop $loopDevice $2
          is_mounted $2 || /system/bin/toybox mount -t ext4 -o loop $loopDevice $2
        fi
        is_mounted $2 && break
      fi
    done
  fi
  echo "$loopDevice" > /tmp/loopDevice
  if ! is_mounted $mountPath; then
    echo -e "\n(!) $IMG mount failed... abort\n"
    exit 1
  fi
}

mnt() {
  echo "Mounting Magisk to $mountPath...";
  mount | grep -qi /magisk && echo "Already mounted! Exiting w/o errors." & exit 0;
  
  mount /data 2>/dev/null
  mount /cache 2>/dev/null
  
  if [ ! -d /data/adb/magisk ] && [ ! -d /data/magisk ]; then
  	echo -e "\n(!) No Magisk installation found or installed version is not supported\n"
  	exit 1
  fi
  
  [ -d $tmp ] && rm -rf $tmp
  mkdir $tmp
  
  [ -d /data/adb/magisk ] && IMG=/data/adb/magisk.img || IMG=/data/magisk.img
  mount_image $IMG $mountPath
  
  for mod in $(ls_mount_path); do
  	touch "$tmp/$mod"
  done
}

upd() {
  echo "Generating fancy list...";
  [ -d $tmp ] && rm -rf $tmp
  mkdir $tmp
  
  for mod in $(ls_mount_path); do
  	touch "$tmp/$mod"
  done
}

unmnt() {
  echo "Unmounting Magisk...";
  loopTMP=$(cat /tmp/loopDevice)
  umount $mountPath
  losetup -d $loopTMP
  rmdir $mountPath
  [ -d $tmp ] && rm -rf $tmp
}

info() {
  echo "MM GUI for OrangeFox RP";
  echo "by fordownloads";
  echo "Thanks to VR25 @ xda-developers for MM Script";
  echo "---";
  echo "Args:";
  echo "mnt - Mount Magisk to $mountPath";
  echo "upd - Generate fancy list";
  echo "unmnt - Unmount Magisk";
}

case "$1" in
	mnt ) mnt;;
	upd ) upd;;
	unmnt ) unmnt;;
	* ) info;;
esac